services:
    server:
      container_name: server-10.9.0.5
      build:
        context: ./server
        dockerfile: ../docker/ServerDockerfile
      cap_add:
                - ALL
      privileged: true
      networks:
        net-10.9.0.0:
          ipv4_address: 10.9.0.5
      tty: true
      sysctls:
              - net.ipv4.tcp_syncookies=0      
      volumes:
              - ./server:/server
      ports:
      - "8080:8080"

    attacker:
      container_name: attacker
      build:
        context: ./attacker
        dockerfile: ../docker/AttackerDockerfile
      cap_add:
                - ALL
      privileged: true
      tty: true
      volumes:
              - ./attacker:/attacker
      network_mode: host

    user:
      container_name: user
      build:
        context: ./user
        dockerfile: ../docker/UserDockerfile
      cap_add:
                - ALL
      privileged: true
      tty: true
      volumes:
              - ./user:/user
      network_mode: host



networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24         #10.9.0.1 to 10.9.0.254 254 usable addresses



    