services:
    server:
      container_name: server-10.9.0.5
      build:
        context: ./server
        dockerfile: ../docker/ServerDockerfile
      cap_add:
                - ALL
      privileged: true
      networks:
        net-10.9.0.0:
          ipv4_address: 10.9.0.5
      tty: true
      sysctls:
              - net.ipv4.tcp_syncookies=0      
      volumes:
              - ./server:/server

    attacker:
      container_name: attacker-10.9.0.6
      build:
        context: ./attacker
        dockerfile: ../docker/AttackerDockerfile
      cap_add:
                - ALL
      privileged: true
      tty: true
      volumes:
              - ./attacker:/attacker
      network_mode: host

    user:
      container_name: user-10.9.0.7
      image: python:3.13.1
      networks:
        net-10.9.0.0:
          ipv4_address: 10.9.0.7
      tty: true


networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24         #10.9.0.1 to 10.9.0.254 254 usable addresses



    